#GET http://localhost:9060/api/v1/accounts?page=0&size=6&username=admin
GET http://localhost:9060/api/v1/accounts?page=0&size=6
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

### 단건조회
GET http://localhost:9060/api/v1/accounts/1

### 회원수정
PUT http://localhost:9060/api/v1/accounts/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzI0ODMxMDN9.sx4IHtDpXXKtf6ytFq9CsXJLJMIpF348EeX2UfHEe1S_V1v1l7-qZwkRs5T0gU4zuTgxcMRN8cKMwU4CJtwQ5g
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email" : "admin2@gmail.com",
  "username" : "변경해봄",
  "nickname" : "하하",
  "phone" : "01012341234",
  "activated" : false
}

