### 로그인 - 일반유저
POST {{host}}/api/v1/auth/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email": "user@gmail.com",
  "password": "1111"
}

> {%
client.test("로그인 성공 검증", function() {
   client.assert(response.status === 200,  "로그인 실패");
   client.global.set("access_token", response.body.resultData.accessToken);
   client.global.set("access_token", response.body.resultData.refreshToken);
   client.log(client.global.get("access_token"));
});
%}

### 로그인 - 어드민
POST {{host}}/api/v1/auth/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email": "admin@gmail.com",
  "password": "1111"
}
> {%
client.test("로그인 성공 검증", function() {
   client.assert(response.status === 200,  "로그인 실패");
   client.global.set("access_token", response.body.resultData.accessToken);
   client.global.set("refresh_token", response.body.resultData.refreshToken);
   client.log(client.global.get("access_token"));
   client.log(client.global.get("refresh_token"));
});
%}

### 로그인 - 마스터
POST {{host}}/api/v1/auth/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email": "master@camping.kr",
  "password": "1111"
}
> {%
client.test("로그인 성공 검증", function() {
   client.assert(response.status === 200,  "로그인 실패");
   client.global.set("access_token", response.body.resultData.accessToken);
   client.global.set("refresh_token", response.body.resultData.refreshToken);
   client.log(client.global.get("access_token"));
   client.log(client.global.get("refresh_token"));
});
%}

### 회원가입
POST {{host}}/api/v1/auth/sign
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "test",
  "nickname": "nicktest",
  "password": "1111",
  "email" : "test@naver.com",
  "birth" : "19941126",
  "phone" : "01012341234"
}

###
GET {{host}}/api/v1/accounts/1
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
GET {{host}}/api/v1/admin/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzMwMTc5MDh9.Y4GgtsLvJX9ZASM2t_877M_VH-LXVaMSk7pQ_BTZYEmKQR0-Grak-7929t1WaB-XyA_lsFAOudDfcid2h5QBaA

###
POST {{host}}/api/v1/auth/reissue
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "accessToken": "{{access_token}}",
  "refreshToken": "{{refresh_token}}"
}

> {%
client.test("토큰 재발행 검증", function() {
   client.assert(response.status === 200,  "토큰 재발행 실패");
   client.global.set("access_token", response.body.resultData.accessToken);
   client.global.set("refresh_token", response.body.resultData.refreshToken);
   client.log(client.global.get("access_token"));
});
%}
