# 로그인
POST http://localhost:9060/api/v1/auth/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email": "user@gmail.com",
  "password": "1111"
}


### 회원가입 eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNjE0NDg4MzQ0fQ.ixtCR8pv4JDD-nIIvSbrZJfIsLXvacZr-FLqGDPwk1jSuf2nx5Q4ROUBQVSf8HJEjN2zbaIqXooLroaNr36LDw
POST http://localhost:9060/api/v1/auth/sign
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "admin",
  "password": "1111",
  "email" : "test@naver.com",
  "age" : "15",
  "activated" : "false"
}

###
GET http://localhost:9090/api/v1/accounts/1
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
GET http://localhost:9060/api/v1/admin/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDkzMzgzMH0.vqrihkiLv4NOxD1_tv5E88enyzxd1UjVih6C1YginK0C7jHaMkykOdGAOoz7llsoDLSXp700IL7OopRa6gx6kg

###
POST http://localhost:9060/api/v1/auth/reissue
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY3MDkzMzgzMH0.vqrihkiLv4NOxD1_tv5E88enyzxd1UjVih6C1YginK0C7jHaMkykOdGAOoz7llsoDLSXp700IL7OopRa6gx6kg",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NzA5MzM4MzB9.aFULpWTaRZ5hE0uq1XSTW7gxpWQ5Ri480GBjy01lfQRf6Fv14l7_AailIlpnG1G-_XVGLbmOdzUpuWOcD3BkOg"
}
