# 로그인
POST http://localhost:9060/api/v1/auth/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "email": "user@gmail.com",
  "password": "1111"
}


### 회원가입 eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNjE0NDg4MzQ0fQ.ixtCR8pv4JDD-nIIvSbrZJfIsLXvacZr-FLqGDPwk1jSuf2nx5Q4ROUBQVSf8HJEjN2zbaIqXooLroaNr36LDw
POST http://localhost:9060/api/v1/auth/sign
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username": "test",
  "nickname": "nicktest",
  "password": "1111",
  "email" : "test@naver.com",
  "birth" : "19941126",
  "phone" : "01012341234"
}

###
GET http://localhost:9090/api/v1/accounts/1
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
GET http://localhost:9060/api/v1/admin/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzE0NTg2MjZ9.MAnxXp-sOPPyRUJ9IagR_kbOMU3GhwrafWU2EXs3EvYavAron8bEWqIBCtH24AEoTly9bUyeoYgDpOqVmFRp5g

###
POST http://localhost:9060/api/v1/auth/reissue
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX1VTRVIiLCJleHAiOjE2NzE0NTgyNDB9.1okYsJse4FAHFOvhRXn_slJdnpuZjDE7YjcyS9YB3tpIJSCqk9dfMjydCyGKdQXRvc346amnhMFfyU1VwNidyA",
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE2NzE1NDI4NDB9.eH5BbIwxdQiecwJ_P0YnVICwCNe6FuNFtpcIZ6tkTusIGC0UUJjORm_c3uX8gSxqH_srOJYIaClMnd6Z_waOXA"
}
