###
GET {{host}}/api/v1/menus
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json

###
POST {{host}}/api/v1/menus
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
"menuName": "menu1",
"icon": "icon1",
"path" : "path1",
"menuSeq" : 1,
"menuLevel" : 1,
"menuUseYn" : "Y"
}

###
DELETE {{host}}/api/v1/menus/17
Content-Type: application/json
X-Requested-With: XMLHttpRequest

###
PUT {{host}}/api/v1/menus/17
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "id" : 17,
  "menuName": "menu1",
  "icon": "icon1",
  "path" : "path1",
  "menuSeq" : 1,
  "menuLevel" : 1,
  "menuUseYn" : "Y"
}