GET {{host}}/api/v1/products?page=0&size=10&startDate=20220101&endDate=20230303&startRegDate=20220101&endRegDate=20240101&keywordType=0&keywordText=테스트
Content-Type: application/json
X-Requested-With: XMLHttpRequest
Accept: application/json
Authorization: Bearer {{access_token}}